### ISSUE TITLE
Any plan for support persistence feature？

### ISSUE THREAD

**Issue by qqke** [kang-sw/egui-data-table#12]
Supports persistence features such as saving sorting, column position, column size, whether columns are hidden or not, etc.
I think this is a very friendly feature！

**Comment by kang-sw** [comment]
Well there was no specific plan on implementing something, but it sounds viable. I'll see what can be persisted. Thanks for suggestion!

**Comment by kang-sw** [comment]
Implemented and published as v0.2.2.

You can simply override `Viewer::persist_ui_state` to enable persistency feature.
