### ISSUE TITLE
the trait bound `egui_data_table::Renderer<'_, MailInfo, Viewer>: eframe::egui::Widget` is not satisfied

### ISSUE THREAD

**Issue by Sansan0990** [kang-sw/egui-data-table#17]
my cargo.toml dependenies
`[workspace.dependencies]
egui = {version = "0.28"}
eframe = {version = "0.28" ,features = ["default"]}
egui_extras ={version = "0.28",features = ["all_loaders"]}
egui-data-table = {version = "0.2.2"}
`
my code is
` ui.add(egui_data_table::Renderer::new(
            &mut self.mail_table,
            &mut self.mail_viewer,
        ));`
when I build program will report infomation 

`error[E0277]: the trait bound `egui_data_table::Renderer<'_, MailInfo, Viewer>: eframe::egui::Widget` is not satisfied
    --> statistics\src\lumao_app.rs:262:16
     |
262  |           ui.add(egui_data_table::Renderer::new(
     |  ____________---_^
     | |            |
     | |            required by a bound introduced by this call
263  | |             &mut self.mail_table,
264  | |             &mut self.mail_viewer,
265  | |         ));
     | |_________^ the trait `for<'a> FnOnce<(&'a mut eframe::egui::Ui,)>` is not implemented for `egui_data_table::Renderer<'_, MailInfo, Viewer>`, which is required by `egui_data_table::Renderer<'_, MailInfo, Viewer>: eframe::egui::Widget`
     |
     = help: the following other types implement trait `eframe::egui::Widget`:
               &eframe::epaint::PaintStats
               &mut eframe::egui::Frame
               &mut eframe::egui::Margin
               &mut eframe::egui::Rounding
               &mut eframe::egui::Shadow
               &mut eframe::egui::Stroke
               &mut eframe::epaint::TessellationOptions
               eframe::egui::Button<'_>
             and 14 others
     = note: required for `egui_data_table::Renderer<'_, MailInfo, Viewer>` to implement `eframe::egui::Widget`
note: required by a bound in `eframe::egui::Ui::add`
    --> C:\Users\502102\.cargo\registry\src\rsproxy.cn-0dccff568467c15b\egui-0.28.1\src\ui.rs:1309:40
     |
1309 |     pub fn add(&mut self, widget: impl Widget) -> Response {
     |                                        ^^^^^^ required by this bound in `Ui::add`
`
if I change egui version = 0.27 ,eframe version = 0.27 ,egui-extras version = 0.27 ,the program will build success.

**Comment by kang-sw** [comment]
Currently, EGUI 0.28 is not compatible with this crate yet. Until then, you should pick egui 0.27 instead of 0.28. I'd update the dependency soon.

**Comment by kang-sw** [comment]
Updated dependency version and new release v0.3.0. Please try 

```toml
egui-data-table = {version="0.3.0"}
```

and see if it's resolved.

**Comment by kang-sw** [comment]
Closing this issue as upstream dependency is up-to-date.
