### ISSUE TITLE
Improve for better input

### ISSUE THREAD

**Issue by qqke** [kang-sw/egui-data-table#22]
When editing a cell, you must click into it to make edits. Can this be improved to allow for more seamless editing, similar to how it works in Excel?
![image](https://github.com/user-attachments/assets/3f4d0c11-c2ea-4e8d-ae6d-62d1fdcd31d6)

**Comment by kang-sw** [comment]
I'll see if I can reduce it to work with single click.

**Comment by kang-sw** [comment]
You can now enable this by modifying style options.


```rust
egui_data_table::Renderer::new(&mut self.table, &mut self.viewer)
    .with_style_modify(|style| {
        style.single_click_edit_mode = true;
    })
    .show(ui);
```
