### ISSUE TITLE
 Selection visuals should be displayed more clearly

### ISSUE THREAD

**Issue by qqke** [kang-sw/egui-data-table#23]
The selection state should be displayed more clearly, rather than the current white border.
![image](https://github.com/user-attachments/assets/9fc2f130-6b08-4436-aca5-575130fcc143)
It might be better to have a selection state where the focus doesn't leave the cell.
![image](https://github.com/user-attachments/assets/8bc492ff-27b4-433e-9c1d-893481196c83)

**Comment by kang-sw** [comment]
Visuals could be improved sooner, could you please explain the 'selection state' one in detail?

**Comment by qqke** [comment]
Wait for Cool Selection visuals.

**Comment by kang-sw** [comment]
Closed by #25
