### ISSUE TITLE
Add some feature like excel

### ISSUE THREAD

**Issue by qqke** [kang-sw/egui-data-table#9]
Can I select multiple rows and columns like in Excel, copy them to the clipboard, and then paste them from the clipboard, just like in Excel?

**Comment by kang-sw** [comment]
While it's a bit suboptimal, you can select multiple cells(or rectangular spans) by clicking(dragging) with ctrl key. You can then copy the cell into internal clipboard, then paste it to any row by the structure keeped. 

However, keep it mind that this data table is strictly schema-based, as you can not copy the contents of 3rd column then paste it into 2nd columns of other row. It always copying the *row* to another *row*. Every cell of the Excel is object, however, in this crate, only the rows are objects, columns are more like properties. 

[In demo page](https://kang-sw.github.io/egui-data-table/), you can test this behavior. Select multiple cells by ctrl+click, then copy it with ctrl+c(warning; it's ctrl key in macos either, not cmd!) select another row's *another* column, paste it with ctrl+v.

**Comment by qqke** [comment]
Thanks, I've figured out how to use it, but there's one other thing about sorting table headers, you have to select the header and it's very hard to select on it.

**Comment by kang-sw** [comment]
Ah, I see. After upgrading to newest egui version, there was some change on focus priority behavior. I thought I've corrected all code to work with new logic, but didn't check it. I'll find way to fix it soon. Thanks for reporting. 😄

**Comment by qqke** [comment]
Thanks,wait for it.I close this issue
